























.build/leonardo/Enerlib/Enerlib.o : lib/Enerlib/Enerlib.cpp
	@echo Enerlib/Enerlib.cpp
	@mkdir -p .build/leonardo/Enerlib
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/Enerlib/Enerlib.cpp
include .build/leonardo/Enerlib/Enerlib.d



.build/leonardo/Enerlib/libEnerlib.a : .build/leonardo/Enerlib/Enerlib.o
	@echo Linking libEnerlib.a
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/leonardo/VirtualWire/VirtualWire.o : /usr/share/arduino/libraries/VirtualWire/VirtualWire.cpp
	@echo VirtualWire/VirtualWire.cpp
	@mkdir -p .build/leonardo/VirtualWire
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/libraries/VirtualWire/VirtualWire.cpp
include .build/leonardo/VirtualWire/VirtualWire.d



.build/leonardo/VirtualWire/libVirtualWire.a : .build/leonardo/VirtualWire/VirtualWire.o
	@echo Linking libVirtualWire.a
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/leonardo/VirtualWire/VirtualWire.o : lib/VirtualWire/VirtualWire.cpp
	@echo VirtualWire/VirtualWire.cpp
	@mkdir -p .build/leonardo/VirtualWire
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/VirtualWire/VirtualWire.cpp
include .build/leonardo/VirtualWire/VirtualWire.d



.build/leonardo/VirtualWire/libVirtualWire.a : .build/leonardo/VirtualWire/VirtualWire.o
	@echo Linking libVirtualWire.a
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/leonardo/arduino/avr-libc/malloc.o : /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/malloc.c
	@echo arduino/avr-libc/malloc.c
	@mkdir -p .build/leonardo/arduino/avr-libc
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/malloc.c
include .build/leonardo/arduino/avr-libc/malloc.d

.build/leonardo/arduino/avr-libc/realloc.o : /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/realloc.c
	@echo arduino/avr-libc/realloc.c
	@mkdir -p .build/leonardo/arduino/avr-libc
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/realloc.c
include .build/leonardo/arduino/avr-libc/realloc.d

.build/leonardo/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
	@echo arduino/WInterrupts.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
include .build/leonardo/arduino/WInterrupts.d

.build/leonardo/arduino/wiring.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
	@echo arduino/wiring.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
include .build/leonardo/arduino/wiring.d

.build/leonardo/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
	@echo arduino/wiring_shift.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
include .build/leonardo/arduino/wiring_shift.d

.build/leonardo/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo arduino/wiring_pulse.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/leonardo/arduino/wiring_pulse.d

.build/leonardo/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
	@echo arduino/wiring_analog.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
include .build/leonardo/arduino/wiring_analog.d

.build/leonardo/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
	@echo arduino/wiring_digital.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
include .build/leonardo/arduino/wiring_digital.d






.build/leonardo/arduino/CDC.o : /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
	@echo arduino/CDC.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
include .build/leonardo/arduino/CDC.d

.build/leonardo/arduino/main.o : /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
	@echo arduino/main.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
include .build/leonardo/arduino/main.d

.build/leonardo/arduino/new.o : /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
	@echo arduino/new.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
include .build/leonardo/arduino/new.d

.build/leonardo/arduino/WString.o : /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
	@echo arduino/WString.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
include .build/leonardo/arduino/WString.d

.build/leonardo/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo arduino/IPAddress.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/leonardo/arduino/IPAddress.d

.build/leonardo/arduino/Print.o : /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
	@echo arduino/Print.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
include .build/leonardo/arduino/Print.d

.build/leonardo/arduino/HID.o : /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
	@echo arduino/HID.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
include .build/leonardo/arduino/HID.d

.build/leonardo/arduino/WMath.o : /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
	@echo arduino/WMath.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
include .build/leonardo/arduino/WMath.d

.build/leonardo/arduino/Tone.o : /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
	@echo arduino/Tone.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
include .build/leonardo/arduino/Tone.d

.build/leonardo/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo arduino/HardwareSerial.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/leonardo/arduino/HardwareSerial.d

.build/leonardo/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
	@echo arduino/USBCore.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
include .build/leonardo/arduino/USBCore.d

.build/leonardo/arduino/Stream.o : /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
	@echo arduino/Stream.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
include .build/leonardo/arduino/Stream.d



.build/leonardo/arduino/libarduino.a : .build/leonardo/arduino/avr-libc/malloc.o .build/leonardo/arduino/avr-libc/realloc.o .build/leonardo/arduino/WInterrupts.o .build/leonardo/arduino/wiring.o .build/leonardo/arduino/wiring_shift.o .build/leonardo/arduino/wiring_pulse.o .build/leonardo/arduino/wiring_analog.o .build/leonardo/arduino/wiring_digital.o .build/leonardo/arduino/CDC.o .build/leonardo/arduino/main.o .build/leonardo/arduino/new.o .build/leonardo/arduino/WString.o .build/leonardo/arduino/IPAddress.o .build/leonardo/arduino/Print.o .build/leonardo/arduino/HID.o .build/leonardo/arduino/WMath.o .build/leonardo/arduino/Tone.o .build/leonardo/arduino/HardwareSerial.o .build/leonardo/arduino/USBCore.o .build/leonardo/arduino/Stream.o
	@echo Linking libarduino.a
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build/leonardo/src/rx.o : .build/leonardo/src/rx.cpp
	@echo src/rx.cpp
	@mkdir -p .build/leonardo/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -Ilib/Enerlib -I/usr/share/arduino/libraries/VirtualWire -I/usr/share/arduino/libraries/VirtualWire/util -I/usr/share/arduino/libraries/VirtualWire/doc -Ilib/VirtualWire -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions -iquote src  -o $@ -c .build/leonardo/src/rx.cpp
include .build/leonardo/src/rx.d







.build/leonardo/firmware.elf : .build/leonardo/src/rx.o .build/leonardo/Enerlib/libEnerlib.a .build/leonardo/VirtualWire/libVirtualWire.a .build/leonardo/VirtualWire/libVirtualWire.a .build/leonardo/arduino/libarduino.a
	@echo Linking firmware.elf
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/leonardo/firmware.hex : .build/leonardo/firmware.elf
	@echo Converting to firmware.hex
	@/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/leonardo/src/dependencies.d .build/leonardo/arduino/dependencies.d .build/leonardo/VirtualWire/dependencies.d .build/leonardo/Enerlib/dependencies.d .build/leonardo/VirtualWire/dependencies.d

all : .build/leonardo/firmware.hex
	@true

